#: font
font_size 13.0
# font_family JetBrainsMono Nerd Font Mono
modify_font  cell_width -1px
modify_font  cell_height 20px
modify_font  underline_position     5
modify_font  strikethrough_position 5
modify_font cell_height 130%


#: windows layout
hide_window_decorations no
inactive_text_alpha 0.4
enabled_layouts splits, stack

#: cursor
cursor_trail 3


#: tab
tab_bar_style        powerline
tab_powerline_style  round
tab_title_template "{index}.{title}{' [' + str(num_windows) + ']' if num_windows > 1 else ''}"
tab_bar_min_tabs 1

#: Color scheme
background_opacity 0.9
background_blur 20


#: OS specific tweaks
macos_option_as_alt yes

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME



#: keymaps
#: tab
map cmd+t        new_tab
map cmd+w        close_tab
map cmd+shift+i  set_tab_title
map cmd+1        goto_tab               1
map cmd+2        goto_tab               2
map cmd+3        goto_tab               3
map cmd+4        goto_tab               4
map cmd+5        goto_tab               5
map cmd+6        goto_tab               6
map cmd+7        goto_tab               7
map cmd+8        goto_tab               8
map cmd+9        goto_tab               9
map cmd+0        goto_tab               10
map cmd+p        goto_tab               -1


#: Font sizes {{{

map cmd+equal  change_font_size all +1.0
map cmd+minus  change_font_size all -1.0
map cmd+0      change_font_size all 0

#: }}}
